# -*- coding: utf-8 -*-
"""appa1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PkN_oDICcdzBy4EwhwQN9PIRVU7MUfTp
"""

import streamlit as st
import pandas as pd
import pickle

# Load Model

model = pickle.load(open("atm_cash_predictor.pkl", "rb"))

st.set_page_config(
page_title="ATM Cash Demand Predictor",
page_icon="🏦",
layout="centered"
)

st.title("🏦 ATM Cash Demand Predictor")
st.markdown(
"Predict the cash required for an ATM on the next day using Machine Learning."
)

st.divider()

# ATM Details

atm_id = st.number_input("ATM ID", min_value=1, value=1)

# Day of Week

day_name = st.selectbox(
"Day of Week",
["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
)

day_map = {
"Monday":0,
"Tuesday":1,
"Wednesday":2,
"Thursday":3,
"Friday":4,
"Saturday":5,
"Sunday":6
}

day_of_week = day_map[day_name]

# Time of Day

time_name = st.selectbox(
"Time of Day",
["Morning","Afternoon","Evening"]
)

time_map = {
"Morning":0,
"Afternoon":1,
"Evening":2
}

time_of_day = time_map[time_name]

# Location Type

location_name = st.selectbox(
"Location Type",
["Urban","Semi Urban","Rural"]
)

location_map = {
"Urban":0,
"Semi Urban":1,
"Rural":2
}

location_type = location_map[location_name]

# Weather

weather_name = st.selectbox(
"Weather Condition",
["Sunny","Cloudy","Rainy"]
)

weather_map = {
"Sunny":0,
"Cloudy":1,
"Rainy":2
}

weather_condition = weather_map[weather_name]

# Holiday

holiday = st.selectbox(
"Is it a Holiday?",
["No","Yes"]
)

holiday_flag = 1 if holiday == "Yes" else 0

# Special Event

event = st.selectbox(
"Special Event Nearby?",
["No","Yes"]
)

special_event_flag = 1 if event == "Yes" else 0

st.divider()

# Transaction Information

total_withdrawals = st.number_input(
"Total Withdrawals (₹)",
min_value=0.0
)

total_deposits = st.number_input(
"Total Deposits (₹)",
min_value=0.0
)

previous_day_cash = st.number_input(
"Previous Day Cash Level (₹)",
min_value=0.0
)

nearby_atms = st.number_input(
"Nearby Competitor ATMs",
min_value=0,
value=1
)

st.divider()

# Date Information

month = st.selectbox(
"Month",
list(range(1,13))
)

day = st.selectbox(
"Day",
list(range(1,32))
)

year = st.number_input(
"Year",
min_value=2025,
value=2026
)

if st.button("Predict Cash Demand"):
    input_data = pd.DataFrame({
        'ATM_ID':[atm_id],
        'Day_of_Week':[day_of_week],
        'Time_of_Day':[time_of_day],
        'Total_Withdrawals':[total_withdrawals],
        'Total_Deposits':[total_deposits],
        'Location_Type':[location_type],
        'Holiday_Flag':[holiday_flag],
        'Special_Event_Flag':[special_event_flag],
        'Previous_Day_Cash_Level':[previous_day_cash],
        'Weather_Condition':[weather_condition],
        'Nearby_Competitor_ATMs':[nearby_atms],
        'Month':[month],
        'Day':[day],
        'Year':[year]
    })

    prediction = model.predict(input_data)

    st.success(
        f"Predicted Next-Day Cash Requirement: ₹ {prediction[0]:,.2f}"
    )

