# -*- coding: utf-8 -*-
"""app1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12GFIAvLrZ7pZUGfLVGlMUtlrtxIFvEVC
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import pickle

# Load Model
model = pickle.load(open('atm_cash_predictor.pkl', 'rb'))

# Title
st.title("🏦 ATM Cash Demand Predictor")
st.write("Predict future ATM cash requirements using Machine Learning")

# Inputs
ATM_ID = st.number_input("ATM ID", min_value=1)

Location_Type = st.selectbox(
    "Location Type",
    ["Urban", "Semi-Urban", "Rural"]
)
Day_of_Week = st.number_input("Day of Week")
Holiday_Flag = st.number_input("Holiday Flag (0/1)")
Special_Event_Flag = st.number_input("Special Event Flag (0/1)")
Time_of_Day = st.number_input("Time of Day")
Weather_Condition = st.number_input("Weather Condition")

Total_Withdrawals = st.number_input("Total Withdrawals")
Total_Deposits = st.number_input("Total Deposits")

Nearby_Competitor_ATMs = st.number_input("Nearby Competitor ATMs")
Previous_Day_Cash_Level = st.number_input("Previous Day Cash Level")

Month = st.number_input("Month", min_value=1, max_value=12)
Day = st.number_input("Day", min_value=1, max_value=31)
Year = st.number_input("Year", min_value=2024)

# Prediction Button
if st.button("Predict Cash Demand"):

    input_data = pd.DataFrame({
        'ATM_ID':[ATM_ID],
        'Location_Type':[Location_Type],
        'Day_of_Week':[Day_of_Week],
        'Holiday_Flag':[Holiday_Flag],
        'Special_Event_Flag':[Special_Event_Flag],
        'Time_of_Day':[Time_of_Day],
        'Weather_Condition':[Weather_Condition],
        'Total_Withdrawals':[Total_Withdrawals],
        'Total_Deposits':[Total_Deposits],
        'Nearby_Competitor_ATMs':[Nearby_Competitor_ATMs],
        'Previous_Day_Cash_Level':[Previous_Day_Cash_Level],
        'Month':[Month],
        'Day':[Day],
        'Year':[Year]
    })

    prediction = model.predict(input_data)

    st.success(
        f"Predicted Cash Demand: ₹{prediction[0]:,.2f}"
    )
